### ISSUE TITLE
Node v0.12 cluster change

### ISSUE THREAD

**Issue by danneu** [koajs/cluster#3]
Noticed in the Node v0.12 changelog:

http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/

> - Cluster
>    - Now has two modes of operation, the new default is a round robin distribution mechanism where the master accepts new connections and distributes them to your workers. If you want you can still opt back into the old method where your workers are responsible for acception connections.

Does that mean anything for koa-cluster?

**Comment by jonathanong** [comment]
no idea.
