### ISSUE TITLE
koa v2.0 support?

### ISSUE THREAD

**Issue by RussMax783** [koajs/cluster#7]
Does this work with koa 2.0?

**Comment by jonathanong** [comment]
nope, not yet. PR welcoemd :)

**Comment by roastlechon** [comment]
@jonathanong is there anything in particular missing? I tested it out with a koa@next app and it seems to work just fine.

**Comment by coderhaoxin** [comment]
> is there anything in particular missing?

IMO, no! >_<

**Comment by RussMax783** [comment]
This works for us as well, Since its simply making sure the instances are running there doesn't seem like there's anything koa v2 specific.
